name: webviewx
description: A feature-rich cross-platform webview using webview_flutter for
  mobile and iframe for web. JS interop-ready.
homepage: https://github.com/adrianflutur/webviewx
version: 0.2.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  path: ^1.8.0
  pointer_interceptor: ^0.9.3
  uuid: ^3.0.6
  webview_flutter: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.6.0
